# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 忆星辰 | 博客
favicon: https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/avatar/favicon-cicle.png?x-oss-process=style/WebSiteCover
subtitle: '个人博客'
description: '星辰的个人博客'
keywords: "博客, 游戏, 开发, Unity, Laya, Cocos, JavaScript, TyptScript, 前端"
author: Akimoto
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.extingstudio.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - "tools/**"
  - "bangumis/index.html"
  - "album/index.md"
# will output `source/mypage/index.html` and `source/mypage/code.js` without altering them.

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 15
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:


baidu_analytics_key: e98a157d14b712d66463073d921b0253

google_analytics_key: UA-124641144-1

# hexo-helper-live2d
live2d:
  enable: false
  scriptFrom: local
  model:
    use: live2d-widget-model-tororo #模型选择
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    position: left  #模型位置
    width: 150       #模型宽度
    height: 300      #模型高度
    superSample: 2
    hOffset: 40     # 横坐标偏移
    vOffset: 50     # 纵坐标偏移
  mobile:
    show: false      #是否在手机端显示
    scale: 0.5
  react:
    opacityDefault: 1
    opacityOnHover: 0.2
  dialog: 
    enable: true
    hitokoto: true
    # script:
    #   'every idle 10s': 'text1'
    #   'tap face': 'text2'
    #   'tap body': 'text3'

# 压缩 Hexo-all-minifier
all_minifier: true

webPushNotification:
  webpushrKey: "L9-CaP_yXKrdnS0nzTlIa-XOWmx2hmPW4-dkdPKtONo"
  webpushrAuthToken: "11579"
  trackingCode: "BNKbIvI_iJuSO3IFPx6D_gSjEve8q7iuxD8qMSMRfWMq0JSx0xRSadjd-x6TX8XI537fa3c7fGsgeic-ejD6l-o"
# hexo-submit-urls-to-search-engine
hexo_submit_urls_to_search_engine:
  submit_condition: count #链接被提交的条件，可选值：count | period 现仅支持count
  count: 10 # 提交最新的10个链接
  period: 900 # 提交修改时间在 900 秒内的链接
  google: 0 # 是否向Google提交，可选值：1 | 0（0：否；1：是）
  bing: 1 # 是否向bing提交，可选值：1 | 0（0：否；1：是）
  baidu: 1 # 是否向baidu提交，可选值：1 | 0（0：否；1：是）
  txt_path: submit_urls.txt ## 文本文档名， 需要推送的链接会保存在此文本文档里
  baidu_host: https://www.extingstudio.com ## 在百度站长平台中注册的域名
  baidu_token: CzmiCGynNrcFpWgM ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  bing_host: https://www.extingstudio.com ## 在bing站长平台中注册的域名
  bing_token: 119644a832c147ecae468bd1e3f92253 ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  google_host: https://www.extingstudio.com ## 在google站长平台中注册的域名
  google_key_file: myblog-287806-0dc315877e33.json #存放google key的json文件，放于网站根目录（与hexo _config.yml文件位置相同），请不要把json文件内容直接发布在公众仓库里!
  replace: 0  # 是否替换链接中的部分字符串，可选值：1 | 0（0：否；1：是）
  find_what: http://www.extingstudio.com/
  replace_with: http://www.extingstudio.com/

# # hexo-backup 插件
# backup:
#     type: git
#     theme: volantis
#     repository:
#        github: git@github.com:BillScott1024/ESBlogRepo.git,backup
#        # gitcafe: git@github.com:xxx/xxx.git,branchName


# 追番页 更新 hexo bangumi -u hexo-bilibili-bangumi
bangumi:
  enable: true    # 是否启用
  path: bangumis/index.html # 番剧页面路径，默认bangumis/index.html
  vmid: 7057062 # 哔哩哔哩番剧页面的vmid(uid)
  title: '追番记录' # 该页面的标题
  quote: '老二次元了~ ( ゜- ゜)つロ' #  写在页面开头的一段话,支持 html 语法
  show: 1 # 初始显示页面：0: 想看,1: 在看,2: 看过，默认为1
  loading: https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/icon/img-loading-bilibili.gif  # 图片加载完成前的 loading 图片
  metaColor: (0, 150, 216)
  color: (0, 150, 216)
  webp: true # 番剧封面使用webp格式(此格式在safari浏览器下不显示，但是图片大小可以缩小 100 倍左右)
  progress: false # 获取番剧数据时是否显示进度条，默认true

use_cdn: true

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo:
      github: git@github.com:BillScott1024/billscott1024.github.io.git,master
      coding: git@e.coding.net:extingstudio1/extingstudio1/extingstudio1.git,master
      # gitee: git@gitee.com:exting/exting.git,master
  # 这是新加的主动推送
  - type: cjh_google_url_submitter
  - type: cjh_bing_url_submitter
  - type: cjh_baidu_url_submitter

# 可以在无需修改主题文件的情况下在 head 和 body 中添加各种标签。
# meta 和 link 对应 head 中的 <meta> 和 <link> 标签。script 可以在 body 末尾导入 js 文件。

import:
  meta:
    # - <meta name="msapplication-TileColor" content="#ffffff">
  link:
    # - <link rel="apple-touch-icon" sizes="180x180" href="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png">
    # - <script async="" referrerpolicy="no-referrer" type="text/javascript" src="//cdn.jsdelivr.net/npm/leancloud-storage@3/dist/av-min.js"></script>
    # swal alert 2的动画样式
    # - <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@4.0.0/animate.min.css" />
  script:
    # - <script async="" referrerpolicy="no-referrer" type="text/javascript" src="//cdn.jsdelivr.net/npm/leancloud-storage@3/dist/av-min.js"></script>
    # 51La 统计
    - '<script type="text/javascript" src="https://js.users.51.la/20919671.js"></script>'
    # U-Meng 统计
    # - <script type="text/javascript">document.write(unescape("%3Cspan id='cnzz_stat_icon_1279216587'%3E%3C/span%3E%3Cscript src='https://s9.cnzz.com/z_stat.php%3Fid%3D1279216587%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
    # webpushr
    - <script type="text/javascript" src="https://cdn.webpushr.com/sw-server.min.js" ></script>
    # webpushr
    - <!-- start webpushr tracking code --> <script>(function(w,d, s, id) {if(typeof(w.webpushr)!=='undefined') return;w.webpushr=w.webpushr||function(){(w.webpushr.q=w.webpushr.q||[]).push(arguments)};var js, fjs = d.getElementsByTagName(s)[0];js = d.createElement(s); js.id = id;js.src = "https://cdn.webpushr.com/app.min.js";fjs.parentNode.appendChild(js);}(window,document, 'script', 'webpushr-jssdk'));webpushr('setup',{'key':'BNKbIvI_iJuSO3IFPx6D_gSjEve8q7iuxD8qMSMRfWMq0JSx0xRSadjd-x6TX8XI537fa3c7fGsgeic-ejD6l-o' });</script><!-- end webpushr tracking code -->
    # 彩条
    - <!--动态线条背景--><script type="text/javascript"color="112, 128, 144" opacity='0.8' zIndex="-2" count="200" src="//cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js"></script>
    # # 烟花
    # - </canvas> <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/BillScott1024/cdn-blog/js/anime.min.js"></script><canvas class="fireworks" style="position:fixed;left:0;top:0;z-index:99999999;pointer-events:none;"></canvas><script type="text/javascript" src="https://cdn.jsdelivr.net/gh/BillScott1024/cdn-blog/js/firework-0.0.2.min.js"></script>
    # 右键复制版权信息
    - <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/BillScott1024/cdn-blog/js/copy-0.0.8.min.js" ></script>
    # sweetalert2 plugins
    # - <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

