### 自定义 ###


# Navigation Bar
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/avatar/favicon-cicle.png
    icon: https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/avatar/favicon-cicle.png
    title:



############################### Layout ###############################
cover:
  use_for: blog # docs, blog
  scheme: dock # blank (留白), search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: true
    others: false # can be written in front-matter 'cover: true'
  # background: https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/033.jpg
  logo: https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/avatar/favicon-cicle.png
  title: ''
  subtitle: ''
  search: 搜索我的文章🔍 # search bar placeholder
  features:
    - name: 博客
      icon: fas fa-book
      url: ''
    - name: 归档
      icon: fas fa-archive
      url: archives/
    - name: 标签
      icon: fas fa-tags
      url: tags/
    - name: 友链
      icon: fas fa-link
      url: friends/
    - name: 说说
      icon: fas fa-comments
      url: shuoshuo/
    - name: 关于
      icon: fas fa-info-circle
      url: about/

# meta library
meta:
  # 文章标题
  title: # 暂无配置
  # 默认文章作者（可在front-matter中覆盖）
  author:
    avatar: https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/avatar/avatar.jpg
    name: Akimoto
    url: /
  # 文章创建日期
  date:
    icon: fas fa-calendar-alt
    title: '发布于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章更新日期
  updated:
    icon: fas fa-edit
    title: '更新于：'
    format: 'll' # 日期格式 http://momentjs.com/docs/
  # 文章分类
  category:
    icon: fas fa-folder-open
  # 文章浏览计数
  counter:
    icon: fas fa-eye
    unit: '次阅读'
  # 文章评论数量：只支持 valine
  valinecount:
    icon: fas fa-comment-dots
    desc: '条评论' # 条评论
  # 文章字数和阅读时长
  wordcount:
    icon_wordcount: fas fa-keyboard
    icon_duration: fas fa-hourglass-half
  # 文章标签
  tags:
    icon: fas fa-hashtag
  # 分享
  share:
    - id: qrcode # 当id为qrcode时需要安装插件  npm i hexo-helper-qrcode
      img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/wechat.png
    - id: qq
      img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qq.png
    - id: qzone
      img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/qzone.png
    - id: weibo
      img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/weibo.png
    # - id: telegram
    #   img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/128/telegram.png
  # 链接
  btns:
    edit:
      icon: fas fa-edit
      title: 在GitHub上编辑此页
      color: '#888'
    repo: # 源码链接
      icon: fas fa-file-code
      title: 源码
      color: '#508EF2'
    bug: # BUG反馈链接
      icon: fas fa-bug
      title: BUG
      color: '#FE5F58'
    doubt: # 疑问链接
      icon: fas fa-question-circle
      title: 疑问
      color: '#FFBD2B'
    idea: # 建议链接
      icon: fas fa-lightbulb
      title: 建议
      color: '#3DC550'
    faq: # FAQ链接
      icon: fas fa-comments
      title: FAQ
      color: '#29B1C9'
    feedback: # 反馈链接
      icon: fas fa-comment-dots
      title: 反馈
      color: '#1BCDFC'



# widget library
widget:
  # The following can be written in `blog/source/_data/widget.yml`
  # ---------------------------------------
  # blogger info widget
  blogger:
    class: blogger
    display: [desktop, mobile] # [desktop, mobile]
    avatar: https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/avatar/avatar.jpg
    shape: rectangle # circle, rectangle
    url: /about/
    title:
    subtitle:
    jinrishici: true # Poetry Today. You can set a string, and it will be displayed when loading fails.
    social: true
  # ---------------------------------------
  # toc widget (valid only in articles)
  toc:
    class: toc
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-list
      title: 本文目录
    list_number: false
    min_depth: 2
    max_depth: 10
  # ---------------------------------------
  # category widget
  category:
    class: category
    display: [desktop] # [desktop, mobile]
    header:
      icon: fas fa-folder-open
      title: 文章分类
      url: /categories/
  # ---------------------------------------
  # tagcloud widget
  tagcloud:
    class: tagcloud
    display: [desktop, mobile] # [desktop, mobile]
    header:
      icon: fas fa-tags
      title: 热门标签
      url: /tags/
    min_font: 14
    max_font: 35
    color: true
    start_color: '#999'
    end_color: '#555'

  # ---------------------------------------
  # qrcode widget
  donate:
    class: qrcode
    display: [desktop, mobile] # [desktop, mobile]
    header: 
      icon: fas fa-mug-hot
      title: 觉得文章有帮助的话，可以扫码请我喝杯咖啡哦~
    height: 100px  # Automatic height if not set
    fancybox: true
    images:
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/pay/weipayimg.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/pay/alipayimg.jpg
  # ---------------------------------------
  # webinfo widget
  webinfo:
    class: webinfo
    display: [desktop]
    header:
      icon: fas fa-award
      title: 站点信息
    type:
      article:
        enable: true
        text: '文章数目：'
        unit: '篇'
      runtime:
        enable: true
        data: '2017/06/18'    # 填写建站日期
        text: '已运行时间：'
        unit: '天'
      wordcount:
        enable: true
        text: '本站总字数：'   # 需要启用 wordcount
        unit: '字'
      siteuv:
        enable: true
        text: '本站访客数：'   # 需要启用 busuanzi
        unit: '人'
      sitepv:
        enable: true
        text: '本站总访问量：' # 需要启用 busuanzi
        unit: '次'
      lastupd:
        enable: true
        friendlyShow: true    # 更友好的时间显示
        text: '最后活动时间：'
        unit: '日'

  # You can add your own widget here or 'blog/source/_data/widget.yml'
  # class: text, list, grid, qrcode, page, ... see more at https://volantis.js.org/


# 文章布局
article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: solid # hidden, solid, dashed, dotted
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    top_meta: [counter, valinecount, wordcount]
    # ----------------
    # 页脚组件
    footer_widget:
      # ----------------
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fas fa-quote-left
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # ----------------
      # 相关文章，需要安装插件 (for layout: post)
      # npm i hexo-related-popular-posts
      related_posts:
        enable: false
        title: 相关文章
        icon: fas fa-bookmark
        max_count: 5
        # 设为空则不使用文章头图
        placeholder_img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/046.jpg
      # ----------------
      # 版权声明组件 (for layout: post/docs)
      copyright:
        enable: true
        permalink: '本文永久链接是：'
        content:
          - '博客内容遵循 署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0) 协议'
          - permalink
      # ----------------
      # 打赏组件 (for layout: post/docs)
      donate:
        enable: true
        images:
          - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/pay/weipayimg.jpg
          - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/pay/alipayimg.jpg
    # 文章底部信息
    bottom_meta:



# 不久后将被其它设置替代
layout:
  # The following can be written in `blog/source/_data/layout.yml`
  # 文章列表（主页、自定义的列表）布局
  on_list:
    # 列表类页面的侧边栏
    sidebar: [blogger, category, tagcloud, donate, webinfo]
  # 页面布局
  on_page:
    # 文章页面主体元素，你也可以在页面的Front-matter中设置
    body: [article, comments]
    # 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
    # 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
    # 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
    meta:
      header: [title, author, category, date, wordcount, counter]
      footer: [updated, tags, btns, share]
    # 文章页面的侧边栏
    sidebar: [qrcode, toc]


footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, analytics, info, copyright, record]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fas fa-envelope
      url: mailto:jaxsonwang@foxmail.com
    - icon: fab fa-github
      url: https://github.com/BillScott1024/
    - icon: fas fa-headphones-alt
      url: https://music.163.com/#/user/home?id=63035382
    # - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/64/qq.png
    #   url: /
    # - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/64/qzone.png
    #   url: /
    # - img: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/64/weibo.png
    #   url: /
    # - avatar: https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/logo/64/wechat.png
    #   url: /
  # site source
  source: https://github.com/BillScott1024/billscott1024.github.io
  # analytics using leancloud
  analytics: >
    <span id="lc-sv">本站总访问量为 <span id='number'><i class="fas fa-circle-notch fa-spin fa-fw" aria-hidden="true"></i></span> 次</span>
    <span id="lc-uv">访客数为 <span id='number'><i class="fas fa-circle-notch fa-spin fa-fw" aria-hidden="true"></i></span> 人</span>
  # site copyright
  copyright: '[Copyright © 2017-2020 XXX](/)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'

  # 备案信息
  record: '<div style="width:300px;margin:0 auto; padding:20px 0;"> <a style="display:inline-block;text-decoration:none;height:20px;line-height:20px;"><img src="/images/beian.png" style="float:left;"/><p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 0px; color:#939393;">鄂公网安备 42011102002596号</p></a></div>'




############################### Plugins ###############################
plugins:
 ######## Plugins to improve loading speed:
  # 图片懒加载
  # https://www.npmjs.com/package/vanilla-lazyload
  lazyload:
    enable: true
    js: https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.1.0/dist/lazyload.min.js
    onlypost: true
    loadingImg: https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/icon/img-loading-bilibili.gif # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/placeholder/c617bfd2497fcea598e621413e315c368f8d8e.svg
    blurIn: true # 模糊加载效果 （loadingImg为空时有效）


  # npm i hexo-wordcount
  wordcount: true #true

  # Slide Background
  backstretch:
    enable: true # true
    js: https://cdn.jsdelivr.net/npm/jquery-backstretch@2.1.18/jquery.backstretch.min.js
    position: cover       # cover: sticky on the cover.   fixed: Fixed as background for the site.
    shuffle: true         # shuffle playlist
    duration: 10000       # Duration (ms)
    fade: 1500            # fade duration (ms) (Not more than 1500)
    images:               # For personal use only. At your own risk if used for commercial purposes !!!
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/001.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/002.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/003.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/004.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/005.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/006.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/012.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/016.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/019.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/025.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/033.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/034.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/035.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/038.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/039.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/042.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/046.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/051.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/052.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/054.jpg
      # - https://cdn.jsdelivr.net/gh/volantis-x/cdn-wallpaper-minimalist/2020/056.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-001.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-002.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-003.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-004.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-005.png
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-006.png
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-007.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-008.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-009.png
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-010.png
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-011.png
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-012.jpg
      - https://es-blogimg.oss-cn-hangzhou.aliyuncs.com/img/background/cover-013.png

  # APlayer is only available in mainland China.
  # APlayer config: https://github.com/metowolf/MetingJS
  aplayer:
    enable: true
    js:
      - https://cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js
      - https://cdn.jsdelivr.net/npm/meting@2.0/dist/Meting.min.js
    # Required
    server: netease   # netease, tencent, kugou, xiami, baidu
    type: playlist    # song, playlist, album, search, artist
    id: 3136952023    # song id / playlist id / album id / search keyword
    # Optional
    fixed: true      # enable fixed mode
    theme: '#1BCDFC'  # main color
    autoplay: true   # audio autoplay
    order: random       # player play order, values: 'list', 'random'
    loop: all         # player loop play, values: 'all', 'one', 'none'
    volume: 0.5       # default volume, notice that player will remember user setting, default volume will not work after user set volume themselves
    list_max_height: 320px # list max height
    list_folded: true
  pjax:
    enable: true
    timeout: 5000        # The timeout in milliseconds for the XHR requests. Set to 0 to disable the timeout.
    cacheBust: false     # When set to true, Pjax appends a timestamp  to skip the browser cache.
    animation: nprogress # nprogress, circle
    banUrl:              # 被屏蔽的 url 地址将不启用 pjax 跳转，可以在控制台下使用 window.location.pathname 获取
      # - '/about/index.html'
      - '/shuoshuo/'


  # Artitalk https://artitalk.js.org
  # 配置过程请参考：https://artitalk.js.org/doc.html
  # 除appID和appKEY外均为选填项
  Artitalk:
    enable: true # true为开启，false为关闭
    appID: V6xXL9F4DfrCwRJ6bLRqm65X-MdYXbMMI # your appID
    appKEY: TTnnUy9nwnTr9s61kGX78zEY # your appKEY
    # severurl:  #leancloud绑定的安全域名，使用国际版的话不需要填写
    # slanguage: # 语言设置，zh为汉语，en为英语，es为西班牙语。默认为汉语
    # per: #每页说说的显示数量
    # placeholder1: #在编辑说说的输入框中的占位符
    # placeholder2: #自定义头像url的输入框的占位符
    # lazy: #加载动画的开关，1为开，0为关，默认为开
    # bgimg: #说说输入框背景图片url
    # color1: #说说背景颜色1&按钮颜色1
    # color2: #说说背景颜色2&按钮颜色2
    # color3: #说说字体颜色
  ##################################



############################### Comments ###############################
comments:
  path:                    # 全局评论地址 仅支持 valine , miniValine , disqus , gitalk
  placeholder: 粘贴图片到此处可以自动上传，请填写邮箱以收到及时回复哦~  # 评论占位提示 仅支持 valine & miniValine
  title: <i class='fas fa-comments'></i> 评论
  subtitle:
  service: valine # valine, minivaline, disqus, gitalk, vssue, livere, isso, hashover
  # Valine
  # https://valine.js.org/
  valine: # 请将 appId appKey 修改为自己的，否则评论数据是共享的。
    appId: p9EoaNrAJAtz2IlbAp0sRau5-gzGzoHsz # your appId
    appKey: u1u31xRPwMb606uCUaaCaV3A # your appKey
    # js: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
    meta: nick,mail,link # valine comment header info
    requiredFields: ['nick','mail']
    enableQQ: true # Unstable avatar link
    avatar: robohash # gravatar style https://valine.js.org/avatar
    pageSize: 10 # comment list page size
    lang: zh-cn
    highlight: true
    visitor: true
    mathJax: false



# 自定义右键菜单
rightmenu:
  enable: false
  # hr: 分割线, music: 音乐控制器
  layout: [home, help, examples, contributors, hr, source_docs, source_theme, hr, print, hr, music]
  # 可选功能项
  print:
    name: 打印页面
    icon: fa fa-print
    onclick: document.execCommand('print')
  # 自定义菜单的格式如下
  help:
    name: 常见问题
    icon: fa fa-question
    url: https://volantis.js.org/faqs/
  examples:
    name: 示例博客
    icon: fa fa-rss
    url: https://volantis.js.org/examples/
  contributors:
    name: 加入社区
    icon: fa fa-fan fa-spin
    url: https://volantis.js.org/contributors/
  source_docs:
    name: 本站源码
    icon: fa fa-code-branch
    url: https://github.com/volantis-x/volantis-docs/
  source_theme:
    name: 主题源码
    icon: fa fa-code-branch
    url: https://github.com/volantis-x/hexo-theme-volantis/


############################### Search ###############################
# To use hexo search, you need to install the following plugins:
# npm i hexo-generator-search hexo-generator-json-content
search:
  enable: true
  service: hexo  # hexo, google, algolia, azure, baidu
  # js: https://cdn.jsdelivr.net/gh/volantis-x/cdn-volantis@3.0/js/search.js
  google:
    apiKey:
    engineId:
  algolia:
    applicationID:
    apiKey:
    indexName:
  azure:
    serviceName:
    indexName:
    queryKey:
  baidu:
    apiId:

analytics:
  busuanzi: https://cdn.jsdelivr.net/gh/volantis-x/cdn-busuanzi@2.3/js/busuanzi.pure.mini.js
  leancloud:
    app_id: OcH33On9kof4QnMnSaAOmDhj-MdYXbMMI
    app_key: V50w1D4JtUK9s3VxbnTtg5XJ
    custom_api_server: # 一般不需要写，除非自定义了 API Server
