name: Blog CI/CD
 
on: [repository_dispatch]
 
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: macos-latest # ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
 
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
 
    - name: Install dependencies
      run: |
        cd Blog/
        npm install
        npm install hexo-cli@latest -g
        npm install yuque-hexo@latest -g
        npm install nunjucks@latest -g
        npm un hexo-renderer-marked
        npm i hexo-renderer-markdown-it -g
        npm install markdown-it-emoji -g

        yuque-hexo sync
    - name: Generate files
      run: |
        cd Blog/
        hexo generate
       
    # from https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        external_repository: BillScott1024/billscott1024.github.io
        publish_branch: master
        publish_dir: ./public
        commit_message: ${{ github.event.head_commit.message }}
