name: Blog CI/CD
 
on: [repository_dispatch]
 
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: macos-latest # ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
 
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
 
    - name: Install dependencies
      run: |
        cd Blog/
        npm install
        npm install hexo-cli@latest -g
        npm install yuque-hexo@latest -g
        npm install nunjucks@latest -g
        npm un hexo-renderer-marked
        npm i hexo-renderer-markdown-it -g
        npm install markdown-it-emoji -g
        npm run start

    - name: Setup Git Infomation
      run: |
       git config --global user.name 'GA-YuQue-To-Hexo'
       git config --global user.email 'jaxsonwang@foxmail.com'


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: BillScott1024/billscott1024.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
        commit_message: ${{ github.event.head_commit.message }}
        
    - name: Deploy To Coding Pages
      env: 
        Coding_Pages: git@e.coding.net:extingstudio1/extingstudio1/extingstudio1.git
        Coding_Token: ${{ secrets.token_CodingAPI }}
        Coding_Username: ${{ secrets.Username_Coding }} 
      run: | 
          git clone https://${Coding_Username}:${Coding_Token}@${Coding_Pages} .coding_pages
          cd .coding_pages 
          git checkout master
          cd ../ 
          rm -r ./public/.git/
          mv .coding_pages/.git/ ./public/
          cd ./public/
          git add . 
          git commit -F ../commit-message.log
          git push --force --quiet "https://${Coding_Username}:${Coding_Token}@${Coding_Pages}" master:master

