name: Blog CI/CD
 
on: [repository_dispatch]
 
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: macos-latest # ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
 
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
 
    - name: Install dependencies
      run: |
        cd Blog/
        npm install -g cnpm --registry=https://registry.npm.taobao.org
        cnpm install
        cnpm install hexo-cli@latest -g
        cnpm install yuque-hexo@latest -g
        cnpm install nunjucks@latest -g
        cnpm un hexo-renderer-marked
        cnpm i hexo-renderer-markdown-it -g
        cnpm install markdown-it-emoji -g

        yuque-hexo sync
    - name: Generate files
      run: |
        cd ..
        cd Blog/
        hexo generate
        
    - name: Setup Git Infomation
      run: |
       git config --global user.name 'GA-YuQue-To-Hexo' 
       git config --global user.email 'jaxsonwang@foxmail.com'
       
    - name: Deploy To Github Pages
      env: 
       Github_Pages: github.com/BillScott1024/billscott1024.github.io
       Github_Token: ${{ secrets.token_GithubAPI }}
      run: |
        cd ..
        git clone https://${Github_Pages} .github_pages
        cd .github_pages
        git checkout master
        cd ../
        ls
        mv .github_pages/.git/ ./public/
        cd ./public/
        ls
        git status
        git add -A
        git status
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${Github_Token}@${Github_Pages}" master:master
