name: Blog CI/CD
 
on: [repository_dispatch]
 
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: macos-latest # ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
 
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
 
    - name: Install dependencies
      run: |
        cd Blog/
        npm install hexo-cli -g
        npm install yuque-hexo -g
        npm install
        npm install -g npm-check
        npm-check
        npm install -g npm-upgrade
        npm-upgrade
        npm-check -u
        yuque-hexo sync
    - name: Generate files
      run: |
        cd Blog/
        hexo generate
       
    - name: Deploy blog
      run: |
        cd ..
        git clone "https://${{ secrets.GH_REF }}" deploy_git
        mv ./deploy_git/.git ./public/
        cd ./public
        git config user.name "Akimoto"
        git config user.email "jaxsonwang@foxmail.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --quiet "https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REF }}" master:master
